doc/add_api_comments
AppLovin/AppLovin-MAX-Flutter pull request #42
Opened 2022-08-24 07:40 UTC by alhiwatan

This PR includes:

- Added comments to the public APIs and fields.
- Exported ad_classes.dart for dartdoc to generate.

Tried to follow the dart doc guide:

https://dart.dev/guides/language/effective-dart/documentation

2022-08-24 15:33 UTC, PLP-Consulting requested changes

2022-08-24 15:33 UTC, PLP-Consulting commented on applovin_max/lib/applovin_max.dart
> +  /// Sets an [AdViewAdListener] listener that notifies ad events.
How about:
> Sets an [AdViewAdListener] listener with which you can receive notifications about ad events.

2022-08-24 15:33 UTC, PLP-Consulting commented on applovin_max/lib/applovin_max.dart
> +  /// [](https://dash.applovin.com/documentation/mediation/flutter/getting-started/banners#displaying-a-banner)
Missing link text

2022-08-24 15:33 UTC, PLP-Consulting commented on applovin_max/lib/src/ad_listeners.dart
>    final Function(MaxAd ad) onAdDisplayedCallback;
These three functions are missing documentation

2022-08-25 04:50 UTC, alhiwatan commented on applovin_max/lib/applovin_max.dart
> +  /// See [ConsentDialogState] for the state of a consent dialog.
Would this work?

```
  /// Returns an integer that encodes the state of the consent dialog.
  ///
  /// To learn more about how this information is encoded in the integer, see [ConsentDialogState].
  ///
  /// [Consent Flags in GDPR and Other Regions](https://dash.applovin.com/documentation/mediation/flutter/getting-started/privacy#consent-flags-in-gdpr-and-other-regions)
  static Future<int?> getConsentDialogState() {
    return channel.invokeMethod('getConsentDialogState');
  }
```

2022-08-25 04:50 UTC, alhiwatan commented on applovin_max/lib/applovin_max.dart
> +  /// Sets whether or no the user has provided consent for interest-based advertising.
done

2022-08-25 04:54 UTC, alhiwatan commented on applovin_max/lib/applovin_max.dart
> +  /// Sets whether or not the user has opted out of interest-based advertising.
Updated.

2022-08-25 07:39 UTC, thomasmso commented on applovin_max/lib/applovin_max.dart
> +  /// Updates the banner position for a given ad unit id.
cc @christophercong re: recent api doc changes with Ad Unit ID references

2022-08-25 07:40 UTC, thomasmso commented on applovin_max/lib/applovin_max.dart
> +  /// Destroys the banner for a given ad unit id.
(cleans up system resources allocated for the banner)

2022-08-25 09:12 UTC, alhiwatan commented on applovin_max/lib/applovin_max.dart
> +  /// Sets your own internal user ID to the current user for the MAX S2S Rewarded Callback requests.
Updated.

2022-08-25 09:12 UTC, alhiwatan commented on applovin_max/lib/applovin_max.dart
> +  ///
Updated.

2022-08-25 09:13 UTC, alhiwatan commented on applovin_max/lib/applovin_max.dart
> +  /// Sets an [AdViewAdListener] listener that notifies ad events.
Updated.

2022-08-25 09:20 UTC, alhiwatan commented on applovin_max/lib/applovin_max.dart
> +  /// Sets an extran parameter to the banner for a given ad unit id.
```
  /// Sets an extra parameter to the banner for a given ad unit identification.
  ///
  /// For example, pass "adaptive_banner" and "false" to this method as the key/value pair
  /// to disable Adaptive Banners for the specified [adUnitId.
  ///
  /// [Adaptive Banners](https://dash.applovin.com/documentation/mediation/flutter/getting-started/banners#adaptive-banners)
  static void setBannerExtraParameter(String adUnitId, String key, String value) {
    channel.invokeMethod('setBannerExtraParameter', {
      'ad_unit_id': adUnitId,
      'key': key,
      'value': value,
    });
  }
```

2022-08-25 09:44 UTC, alhiwatan commented
Have updated the comments, so please review them.  And I have one question.

We have two styles of specifying ad unit id,  'with the specified [adUnitId]' and 'for a given ad unit identification'.   For example.

```
1.  /// Sets an ad placement name for the MREC with the specified [adUnitId].
2.  /// Updates the MREC position for a given ad unit identification.
```

Either way looks okay but which one should we go for?   Or does it depend?

2022-08-25 14:30 UTC, PLP-Consulting commented
> Have updated the comments, so please review them. And I have one question.
> 
> We have two styles of specifying ad unit id, 'with the specified [adUnitId]' and 'for a given ad unit identification'. For example.
> 
> ```
> 1.  /// Sets an ad placement name for the MREC with the specified [adUnitId].
> 2.  /// Updates the MREC position for a given ad unit identification.
> ```
> 
> Either way looks okay but which one should we go for? Or does it depend?

I'd recommend using the same phrasing across all the various methods. Of those two, I prefer the first one ("...with the specified [adUnitId].")

2022-08-25 14:31 UTC, PLP-Consulting commented on applovin_max/lib/src/ad_classes.dart
> +  /// The creative id tied to the ad, if any. You can report creative issues to the corresponding ad network using this id.
Looks like there are still a few lowercased "id"s.

2022-08-26 01:55 UTC, alhiwatan commented
Updated, please review.

2022-08-26 14:05 UTC, PLP-Consulting approved these changes

2022-08-26 19:17 UTC, thomasmso approved these changes
Looks amazing, thanks @PLP-Consulting / @alhiwatan

2022-08-26 19:17 UTC, merged